### ISSUE TITLE
Receiving `KeyError: 'Id'` and nothing is converted in the output file.

### ISSUE THREAD

**Issue by pseudacris** [ConorSheehan1/uhabits_converter#6]
`found {'name': 'Code', 'freq_den': 1, 'freq_num': 1, 'target_value': 100.0}       updating {'freq_num': 1, 
'target_value': 1} ...
Converting habits... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/home/pseudacris/.local/bin/uhabits_converter", line 8, in <module>
    sys.exit(main())
  File "/home/pseudacris/.local/lib/python3.10/site-packages/src/cli.py", line 130, in main
    fire.Fire(cli)
  File "/home/pseudacris/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/pseudacris/.local/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/pseudacris/.local/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/pseudacris/.local/lib/python3.10/site-packages/src/cli.py", line 122, in cli
    errors = c.convert_bool_habit_to_num(
  File "/home/pseudacris/.local/lib/python3.10/site-packages/src/convert.py", line 93, in convert_bool_habit_to_num
    f"UPDATE Habits Set {update_str} where Id IS {habit['Id']} AND TYPE IS {self.bool_habit_type};"
KeyError: 'Id'`

It outputs a file but nothing has been converted.

**Comment by ConorSheehan1** [comment]
Hi @pseudacris, sorry about that. Can you attach the .db file you're using to this issue? That'd help me debug it

**Comment by pseudacris** [comment]
Here you go. Github wouldn't let me load a .db file, so I had to create a repo:

https://github.com/pseudacris/db_for_troubleshooting/blob/main/output.db

**Comment by ConorSheehan1** [comment]
@pseudacris thanks! Could you push the input db too? Or are you using output.db as input?

**Comment by pseudacris** [comment]
No problem. Here you go:

https://github.com/pseudacris/db_for_troubleshooting/blob/main/Loop%20Habits%20Backup%202022-04-22%20072047.db

**Comment by ConorSheehan1** [comment]
Perfect, last thing: could you paste the full command you ran when you got the error here please?

**Comment by pseudacris** [comment]
`╭─pseudacris@codebox ~/Downloads 
╰─$ uhabits_converter
Please choose a .db file to read from: Loop Habits Backup 2022-04-22 072047.db
output.db already exists. Would you like to overwrite it? [y/n]: y
Reading from Loop Habits Backup 2022-04-22 072047.db, writing to output.db
Selecting habits interactively
Would you like to convert archived habits [y/n]: y
[?] Which habits would you like to convert?: 
   o B9
   o CBT
   X Code
 > X Drawabox
   o Everydays
   o Fungus
   o Graphic Design
   o Her
   o How to Learn
   o Meditate 1
   o Meditate 2
   o Mirtazapine
   o Mobility`

I was trying to convert Code and Drawabox

**Comment by ConorSheehan1** [comment]
Hey @pseudacris, that should be fixed in the latest version (v0.2.2), could you re-install and try again?

**Comment by pseudacris** [comment]
It totally worked. Thanks dude :)
